import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faPlay, faPause, faStop, faMusic, faVolumeHigh, faHeart, faStar, faCircle,
  faSquare, faCaretUp, faBolt, faBell, faFlag, faBookmark, faBullseye, faAward,
  faCrown, faFire, faStar as faSparkles, faSun, faMoon, faCloud, faCloudRain, faSnowflake,
  faWind, faFaceSmile, faFaceMeh, faFaceFrown, faCircleExclamation, faCircleCheck,
  faCircleXmark, faCircleInfo, faCircleQuestion, faEye, faEyeSlash, faLock, faUnlock,
  faKey, faShield, faHome, faUser, faUsers, faGear, faWrench, faChartLine,
  faPlus, faMinus, faXmark, faCheck, faChevronUp, faChevronDown, faChevronLeft,
  faChevronRight, faArrowUp, faArrowDown, faArrowLeft, faArrowRight, faDownload,
  faUpload, faPaperPlane, faEnvelope, faPhone, faCamera, faImage, faVideo,
  faFileAudio, faFile, faFolder, faCopy, faClipboard, faTrash, faPen, faLink,
  faCalendar, faClock, faMap, faLocationDot, faGlobe, faWifi, faBatteryFull,
  faPlug, faLightbulb, faMagnet, faPuzzlePiece, faCube, faDatabase, faServer,
  faCode, faTerminal, faBug, faFlask
} from "@fortawesome/free-solid-svg-icons";

export interface IconMapEntry {
  name: string;
  icon: IconDefinition;
}

export const AVAILABLE_ICONS: IconMapEntry[] = [
  { name: 'Play', icon: faPlay },
  { name: 'Pause', icon: faPause },
  { name: 'Stop', icon: faStop },
  { name: 'Music', icon: faMusic },
  { name: 'Volume', icon: faVolumeHigh },
  { name: 'Heart', icon: faHeart },
  { name: 'Star', icon: faStar },
  { name: 'Circle', icon: faCircle },
  { name: 'Square', icon: faSquare },
  { name: 'Triangle', icon: faCaretUp },
  { name: 'Zap', icon: faBolt },
  { name: 'Bell', icon: faBell },
  { name: 'Flag', icon: faFlag },
  { name: 'Bookmark', icon: faBookmark },
  { name: 'Target', icon: faBullseye },
  { name: 'Award', icon: faAward },
  { name: 'Crown', icon: faCrown },
  { name: 'Flame', icon: faFire },
  { name: 'Sparkles', icon: faSparkles },
  { name: 'Sun', icon: faSun },
  { name: 'Moon', icon: faMoon },
  { name: 'Cloud', icon: faCloud },
  { name: 'Umbrella', icon: faCloudRain },
  { name: 'Snowflake', icon: faSnowflake },
  { name: 'Wind', icon: faWind },
  { name: 'Smile', icon: faFaceSmile },
  { name: 'Meh', icon: faFaceMeh },
  { name: 'Frown', icon: faFaceFrown },
  { name: 'AlertCircle', icon: faCircleExclamation },
  { name: 'CheckCircle', icon: faCircleCheck },
  { name: 'XCircle', icon: faCircleXmark },
  { name: 'Info', icon: faCircleInfo },
  { name: 'HelpCircle', icon: faCircleQuestion },
  { name: 'Eye', icon: faEye },
  { name: 'EyeOff', icon: faEyeSlash },
  { name: 'Lock', icon: faLock },
  { name: 'Unlock', icon: faUnlock },
  { name: 'Key', icon: faKey },
  { name: 'Shield', icon: faShield },
  { name: 'Home', icon: faHome },
  { name: 'User', icon: faUser },
  { name: 'Users', icon: faUsers },
  { name: 'Settings', icon: faGear },
  { name: 'Tool', icon: faWrench },
  { name: 'Activity', icon: faChartLine },
  { name: 'Plus', icon: faPlus },
  { name: 'Minus', icon: faMinus },
  { name: 'X', icon: faXmark },
  { name: 'Check', icon: faCheck },
  { name: 'ChevronUp', icon: faChevronUp },
  { name: 'ChevronDown', icon: faChevronDown },
  { name: 'ChevronLeft', icon: faChevronLeft },
  { name: 'ChevronRight', icon: faChevronRight },
  { name: 'ArrowUp', icon: faArrowUp },
  { name: 'ArrowDown', icon: faArrowDown },
  { name: 'ArrowLeft', icon: faArrowLeft },
  { name: 'ArrowRight', icon: faArrowRight },
  { name: 'Download', icon: faDownload },
  { name: 'Upload', icon: faUpload },
  { name: 'Send', icon: faPaperPlane },
  { name: 'Mail', icon: faEnvelope },
  { name: 'Phone', icon: faPhone },
  { name: 'Camera', icon: faCamera },
  { name: 'Image', icon: faImage },
  { name: 'Video', icon: faVideo },
  { name: 'Music2', icon: faFileAudio },
  { name: 'File', icon: faFile },
  { name: 'Folder', icon: faFolder },
  { name: 'Copy', icon: faCopy },
  { name: 'Clipboard', icon: faClipboard },
  { name: 'Trash', icon: faTrash },
  { name: 'Edit', icon: faPen },
  { name: 'Link', icon: faLink },
  { name: 'Calendar', icon: faCalendar },
  { name: 'Clock', icon: faClock },
  { name: 'Map', icon: faMap },
  { name: 'MapPin', icon: faLocationDot },
  { name: 'Globe', icon: faGlobe },
  { name: 'Wifi', icon: faWifi },
  { name: 'Battery', icon: faBatteryFull },
  { name: 'Power', icon: faPlug },
  { name: 'Lightbulb', icon: faLightbulb },
  { name: 'Magnet', icon: faMagnet },
  { name: 'Puzzle', icon: faPuzzlePiece },
  { name: 'Box', icon: faCube },
  { name: 'Database', icon: faDatabase },
  { name: 'Server', icon: faServer },
  { name: 'Code', icon: faCode },
  { name: 'Terminal', icon: faTerminal },
  { name: 'Bug', icon: faBug },
  { name: 'Flask', icon: faFlask },
];

export const getIconByName = (name: string): IconDefinition | null => {
  const entry = AVAILABLE_ICONS.find(i => i.name === name);
  return entry ? entry.icon : null;
};
